# Site settings
title: *folio
name: john kelleher
email: kelleher.john@itsligo.ie
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: /blog # the subpath of your site, e.g. /blog/
url: https://itsligo.github.com/blog # the base hostname & protocol for your site
repo: https://github.com/itsligo/blog  # repo for the code
twitter: johnkelleher
github_username:  jkelleher
website: "jkelleher.me"

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"

# comment out the branches collection if not using branches
collections:
  branches:
    output: true
    permalink: /branch/:path/
  
